name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo 'Hello World' > to_upload-0.1.txt
    - name: Upload binaries to release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "to_upload-*.txt"
        token: ${{ secrets.GITHUB_TOKEN }}